version: "3.8"

services:
  traefik:
    image: traefik:2.9.1
    restart: always
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
      - ./configs/traefik.yml:/etc/traefik/traefik.yml
      - ./configs/dynamic:/etc/traefik/dynamic
      - ./certificates/acme.json:/etc/traefik/acme/acme.json
    networks:
      - routing
  
  quiz-iu:
    image: ghcr.io/madbiceps/quiz-ui:main
    restart: always
    labels:
      - "traefik.enable=true"
      - "traefik.port=80"
      - "traefik.docker.network=quiz-ui"
      - "traefik.http.services.quiz-ui.loadbalancer.server.port=80"
      # https
      - "traefik.http.routers.quiz-ui.rule=Host(`study-quiz.com`)"
      - "traefik.http.routers.quiz-ui.tls=true"
      - "traefik.http.routers.quiz-ui.tls.certresolver=letsencrypt"
      - "traefik.http.routers.quiz-ui.entrypoints=websecure"
      # http (redirect to https)
      - "traefik.http.routers.quiz-ui-http.rule=Host(`study-quiz.com`)"
      - "traefik.http.routers.quiz-ui-http.entrypoints=web"
      - "traefik.http.routers.quiz-ui-http.middlewares=redirect-to-https@file"
    networks:
      - routing

  quiz-service:
    image: ghcr.io/madbiceps/quiz-service:main
    restart: always
    depends_on:
      - service_db
    labels:
      - "traefik.enable=true"
      - "traefik.port=80"
      - "traefik.docker.network=quiz-service"
      - "traefik.http.services.quiz-service.loadbalancer.server.port=80"
      # https
      - "traefik.http.routers.quiz-service.rule=Host(`study-quiz.com`) && Pathprefix(`/api`)"
      - "traefik.http.routers.quiz-service.tls=true"
      - "traefik.http.routers.quiz-service.tls.certresolver=letsencrypt"
      - "traefik.http.routers.quiz-service.entrypoints=websecure"
      # http (redirect to https)
      - "traefik.http.routers.quiz-service-http.rule=Host(`study-quiz.com` ) && Pathprefix(`/api`)"
      - "traefik.http.routers.quiz-service-http.entrypoints=web"
      - "traefik.http.routers.quiz-service-http.middlewares=redirect-to-https@file"
    environment:
      - QUIZ-API__Database_ConnectionString=User ID=${POSTGRES_USER};Password=${POSTGRES_PASSWORD};Host=service_db;Port=5432;Database=appstore;
      - QUIZ-API__JWT_ValidIssuer=https://study-quiz.com
      - QUIZ-API__JWT_ValidAudience=https://study-quiz.com
      - QUIZ-API__JWT_Secret=${JWT_SECRET_KEY}
    networks:
      - routing
      - service_db_net

  service_db:
    image: postgres:15
    restart: always
    environment:
      - POSTGRES_USER=${POSTGRES_USER}
      - POSTGRES_PASSWORD=${POSTGRES_PASSWORD}
      - POSTGRES_DB=appstore
    volumes:
      - "service_db_volume:/var/lib/postgresql/data"
    networks:
      - service_db_net     

networks:
  service_db_net:
  routing:
    driver: bridge
volumes:
  service_db_volume:
