version: '3.3'

services:
  traefik:
    image: traefik:v2.5
    command:
      - "--api.insecure=true"
      - "--providers.docker=true"
      - "--providers.docker.exposedbydefault=false"
      - "--entrypoints.web.address=:80"
    ports:
      - "80:80"
      - "8080:8080"
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
      - ./configs/traefik.yml:/etc/traefik/traefik.yml
      - ./configs/dynamic:/etc/traefik/dynamic
      - ./certificates/acme.json:/etc/traefik/acme/acme.json
  quiz-iu:
    image: docker pull ghcr.io/madbiceps/quiz-ui:main
    restart: always
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.ui.rule=Host(`whoami.local`)"
      - "traefik.http.services.ui.loadbalancer.server.port=80"