version: "2.3"
services:
  database:
    image: postgres:12
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres 
    ports:
      - "5442:5432"
    networks:
    - db_network
    volumes:
    - db-data:/var/lib/postgresql/data
  demo-pgadmin4:
    image: dpage/pgadmin4
    environment:
      PGADMIN_DEFAULT_EMAIL: test@test.com 
      PGADMIN_DEFAULT_PASSWORD: postgres
    ports:
    - "8889:80"
    networks:
    - db_network
networks:
  db_network:
    driver: bridge
    
volumes:
  db-data:
