name: Test Quiz-UI

on:
  push:
    branches: [ "main" ]
    paths-ignore:
      - 'docs/**'
      - 'src/quiz-service'
  pull_request:
    branches: [ "main" ]
  workflow_dispatch:

jobs:

  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3
    - name: Build the Docker image
      working-directory: 'src/quiz-ui'
      run: docker build . --file Dockerfile --tag quiz-ui:$(date +%s)
