name: Docker Image CI

on:
  push:
    branches: [ "main" ]
    paths-ignore:
      - 'docs/**'
      - 'src/quiz-ui'
  pull_request:
    branches: [ "main" ]
   workflow_dispatch:

jobs:

  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3
    - name: Build the Docker image
      working-directory: 'src/quiz-service'
      run: docker build . --file Dockerfile --tag my-image-name:$(date +%s)
